config/routes.rb
Flashcards::Application.routes.draw do
   
  get "flatuipro_demo/index"

   resource :session, only: [:new, :create, :destroy] 
   resources :users
   resources :decks do   
    resources :cards, except: :index
  end

 

  root :to => 'decks#home'

  
end

  # match ':controller(/:action(/:id))(.:format)'

app/models/card.rb
class Card < ActiveRecord::Base
	belongs_to :deck
	attr_accessible :front, :back, :deck_id
end

app/models/deck.rb
class Deck < ActiveRecord::Base
	attr_accessible :name
	has_many :cards
	belongs_to :user
	# scope: :funcion, somefunction
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :decks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  

  def current_user #by this I make this method available for all controllers throug inheritance, its faster tha typing it everytime for each.
  	if (cookies[:user_id])
  		user_id = cookies.signed[:user_id] #because cookie was stored in signed(encrypted) cookie jar. Returns nil if it doesnt exist
  		return User.find_by_id(user_id)
  	end
  end
  helper_method :current_user #when I declare :current_user as a helper method, I make this method available for all views througout my app

  def sign_in(user)#if user exists, it assigns cookie with user id, that enables to pass authenticate tests
    if user
  	cookies.signed[:user_id] = user.id
    else

    end
  end
  def authenticate
  	unless sign_in?
      flash[:failed_login] = " You must be logged in to access the app. Please check make sure you have an account with us and your login info is correct"
  		redirect_to new_session_path
  	end
  end
  def sign_in?
  	current_user #because if it doesnt exist will be nil, thanks to find_by_* method
  end
  helper_method :sign_in?

  def user_exists(user)
    User.find_by_email(user)
  end




 def generate_fixed_cards(deck) #Generates a set of fixed cards for a given deck, then saves them to db

  cards = [{:front=>"Cat", :back=>"Neko"}, {:front=>"Dog", :back=>"Inu"}, {:front=>"Horse", :back=>"Uma"}, {:front=>"Bird", :back=>"Tori"}, {:front=>"Fish", :back=>"Sakana"}, {:front=>"Bear", :back=>"Kuma"}, {:front=>"Dragon", :back=>"Ryuu"}, {:front=>"Octopus", :back=>"Tako"}, {:front=>"Rabbit", :back=>"Usagi"}]
  cards.each do |card|
    new_card = deck.cards.new(card)
    new_card.save
  end

 end




end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	
	def show
		@deck = find_deck 		#should jus use find_deck method, like so: @deck = find_deck
		@card =  @deck.cards.find(params[:id])	#	
	end

	def edit
		@deck = find_deck
		@card = @deck.cards.find(params[:id])
		# @card = Card.find(params[:id])
		# @deck = @card.deck
	end

	def new
		@deck = find_deck 
		@card = @deck.cards.new #I USED CARD.NEW, PROBLEM IS THIS WAY THERES NO LINK BETWEEN CARD AND DECK.
		#WHY NOT JUST CARD.NEW, IN CREATE ACTION THE LINK IS RECREATED SO IT SHOULDNT BE NEEDED HERE....???
	end

	def create
		@deck = find_deck 
		@card = @deck.cards.new(params[:card]) #LINK IS CREATED AGAIN AND PARAMS ADDED, SEEMS LIKE WHAT WAS DONE FROM NEW ACTION IS LOST AND I START FROM SCRATCH
		@card.save
		redirect_to @deck
		#I USED FOLLOWING BAD CODE, BECAUSE I WAS MISSING LINK FROM CARD TO DECK, HAD TO IMPROVISE WITH ATTRIBUTE_UPDATE
		# @card_attr = params[:card].merge({deck_id: params[:deck_id]})
		# @card = Card.new(@card_attr)


	end

	def update
		@deck = find_deck 
		@card = Card.find(params[:id])
		@card_before_update = @card.dup
		@card.update_attributes(params[:card])
		@updated_status = true

	end

	def destroy
		@deck = find_deck 
		@card = Card.find(params[:id])
		@card.destroy
		@card.save
		redirect_to @deck
	end


	private 		#use private so rail nows this is not an action, just an specific method for this class only. Cant be accessed from outside
	def find_deck 
		Deck.find(params[:deck_id]) #replaces Deck.find(params[:deck_id]
		
	end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
	before_filter :authenticate , except: :home #calls this method before doing any action
	def index
		@decks = current_user.decks # switched from @decks = Deck.all, so now it only displays the logged user decks.
	end

	def show
		@deck = find_deck # same as Deck.find(params[:id])
		@cards = @deck.cards
	end

	def new
		@deck = Deck.new
	end

	def create
		@deck = Deck.new(params[:deck])
		@deck.user = current_user
		@deck.save
		redirect_to decks_path
	end

	def edit
		@deck = find_deck
	end

	def update
		@deck = find_deck
		@deck.update_attributes(params[:deck])
		redirect_to decks_path
	end

	def destroy
		@deck = find_deck
		@deck.destroy
		redirect_to decks_path
	end

	def home
		if sign_in?
			redirect_to decks_path
		end
	end

	private

	def find_deck
		@deck = Deck.find(params[:id])
	end

end

app/controllers/flatuipro_demo_controller.rb
class FlatuiproDemoController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		user = User.find_by_email(params[:session][:email]) #same as User.where(email: @email)
		sign_in(user)
		
		redirect_to decks_path
	end
	def destroy
		cookies.delete(:user_id)
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	def create
		if user_exists(params[:user][:email])	 
		  flash[:user_exists] = "Username already exists, please register yourself with a different email."
	      redirect_to new_user_path
	    else
		# @user = User.new(params[:user])
		# @user.decks = Deck.all.dup #insert new deck, fixed name:japanese

		#######Fixed starting deck, and cards#####
		@user = User.new(params[:user])
		# @user.save
		@deck = Deck.new(name: "Japanese")
		# @deck.save
		@deck.user = @user
		@deck.save

		generate_fixed_cards(@deck) #application controllers inherited method
		
		sign_in(@user)#if user exists, it creates a user_id cookie for it

		redirect_to decks_path

		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_controllers_helper.rb
module UserControllersHelper
end

app/views/cards/create.html.erb
tetsing create asdasda 

app/views/cards/edit.html.erb
<p>Updating <p> 

	
	<%= form_for(@card, url: deck_card_path, method: :put)  do |f| %>
	 Front card: <%= f.text_field :front  %>
	 Back card: <%= f.text_field :back  %>
	 Update <%= f.submit "Update card" %>
	 <% end %>

	  <%= link_to("Return to cards", [@deck]) %> 

app/views/cards/new.html.erb
Testing Card Add Feature
<br><br>


	<%= form_for([@deck, @card])  do |f| %>  <!-- I USED BAD CODING @card, url: deck_cards_path(@deck) -->
	 Front card: <%= f.text_field :front  %>
	 Back card: <%= f.text_field :back  %>
	 Update <%= f.submit "Create card" %>
	 <% end %>
	 <br><br>

	  <%= link_to("Return to cards", [@deck]) %>  



	 <!-- Correct url - url: deck_cards_path(@deck) -->


	 <!-- @card, url: deck_cards_path(@deck) -->

app/views/cards/show.html.erb
<h4> The back of the card <b><i> <%= @card.front %> </b></i> is: </h4>

<h1> <i> <%= @card.back %> <i> </h1>

<%= link_to("Return to Cards", @deck) %>

app/views/cards/update.html.erb
<h2> Congratulations!</h2>


<h4> You have succesfully updated the front of your card 
<!-- If cards are equal(no real update), then dont show from "card" to "card"-->
	<% if @card_before_update.front !=  @card.front %>
		from <i><%= @card_before_update.front  %> </i>
	<% end %>
to <i> <%= @card.front %> </i> 
</h4> 

<h4> You have succesfully updated the back of your card 
<!-- If cards are equal(no real update), then dont show from "card" to "card"-->
	<% if @card_before_update.back !=  @card.back %>
		from <i><%= @card_before_update.back  %> </i>
	<% end %>
to <i> <%= @card.back %> </i> 
</h4> 



<br><br>
<div><%= link_to("Return to #{@deck.name} deck", [@deck]) %></div>

app/views/decks/edit.html.erb
<br>
<%= form_for(@deck) do |form|%> 	
<div>			<!-- #FORM BUILDER OBJECT, ITS A HELPER METHOD -->
<%= form.label :name %>	<!-- DISPLAYS NAME COLUMN OF @DECKS AS LABEL -->
<%= form.text_field :name%>
</div>
<%= form.submit "Update Deck" %>

<%end%>
<br>
<%= link_to "return", decks_path %>

app/views/decks/home.html.erb
<p>Welcome to the Flashcards App!</p>

<p>Please sign in if you have an account, or register with us to get one!</p>

app/views/decks/index.html.erb
<h1><b>Welcome to "The Cards Game!"<b></h1>

<% if current_user %>
<h3>Please choose a deck:</h3>
<br>

<div> <%= link_to "Create New Deck", new_deck_path %> </div>
<br><br>
<div>Available Decks </div> <br>
<div> 
<% @decks.each do |d| %>
	<div> 
	
		<%= link_to d.name, d %> 
		<%= link_to "Edit deck", edit_deck_path(d) %>
		<%= link_to "Delete deck", d, method: :delete, confirm: 'You sure about this???' %>

	</div> <br>
	
<% end%> 
<% else %>
<p>Please sign in/register in order to play! <%= link_to "Back to log screen", root_path %></p>

<% end %>
	<% if @user %>
	<%= @user.all.inspect %>
	<% end %>

app/views/decks/new.html.erb
<br>
<%= form_for(@deck) do |form|%> 	
<div>			<!-- #FORM BUILDER OBJECT, ITS A HELPER METHOD -->
<%= form.label :name %>	<!-- DISPLAYS NAME COLUMN OF @DECKS AS LABEL -->
<%= form.text_field :name%>
</div>
<%= form.submit "Create Deck" %>
<%end%>
<br>
<%= link_to "return", decks_path %>

app/views/decks/show.html.erb
<br>
<p>Great Choice!!</p>
<% if true %>
<% end %>
<p>You are currently using the <b><%= @deck.name %></b> deck!! Enjoy!<p>

	<p> This deck contains the following cards: </p>
	<br>
	<% @cards.each do |card| %>
		<p>
		Front: <%= link_to card.front, [@deck, card] %> <!-- 	can also be [card.deck, card]-->

		<%= link_to("Update card", edit_deck_card_path(card.deck, card) ) %> 
		<%= link_to("Delete Card", [@deck, card], method: :delete)%></p> 
		<!-- i used "/decks/#{params[:id]}/cards/#{card.id}"-->

	<% end %>

<p> Now try guessing what each of the back of these cards is! <p>
<%= link_to "Add a new Card", new_deck_card_path(@deck, @card) %>
<br><br><br>
<%= link_to "Return to Home", decks_path %>


<!--link to create card deck_cards_path(@deck)  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<body>
<p>Credits...By Pablo, from Tutorial Videos :), (yep, this looks very anti-esthetic up here xD)
	
</p>

<%if sign_in? %>
	<p> User: <b><%= current_user.email %> </b> 
	<%= link_to "Logout", session_path, method: :delete %>
	</p>
<% else %>
	<div> <%= link_to("Sign in", new_session_path) %> <%= link_to("Sign up", new_user_path) %> </div>
<% end %>

<%= yield %>


</body>
</html>

app/views/users/new.html.erb
Welcome

<% if flash[:user_exists] %>
	<div style="color:red; font-style:italic"> <%=  flash[:user_exists] %> </div> 
	<br>
<% end %>
<%= form_for @user do |form| %>

<p> Email: <%= form.text_field :email %> </p> 
<p> <%= form.submit "Register" %> </p>

<% end %>

<%= link_to "Back to home", root_path %>